version: '3'

services:
  passengerapi:
    image: passengerapi
    build:
      context: .
      dockerfile: PassengerAPI\Dockerfile
      
  identityapi:
    image: identityapi
    build:
      context: .
      dockerfile: IdentityAPI\Dockerfile

  resttestwebapp:
    image: resttestwebapp
    build:
      context: .
      dockerfile: RestTestWebApp\Dockerfile
