version: '3'

services:
  resttestwebapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  passengerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat



