version: '3'

services:
  resttestwebapp:
    image: resttestwebapp
    build:
      context: .
      dockerfile: RestTestWebApp\Dockerfile

  driverapi:
    image: driverapi
    build:
      context: .
      dockerfile: DriverAPI\Dockerfile

